drop policy "Users can insert own profile" on "public"."users";

drop policy "Users can update own profile" on "public"."users";

drop policy "Users can view own profile" on "public"."users";

revoke references on table "public"."users" from "anon";

revoke trigger on table "public"."users" from "anon";

revoke truncate on table "public"."users" from "anon";

revoke references on table "public"."users" from "authenticated";

revoke trigger on table "public"."users" from "authenticated";

revoke truncate on table "public"."users" from "authenticated";

revoke references on table "public"."users" from "service_role";

revoke trigger on table "public"."users" from "service_role";

revoke truncate on table "public"."users" from "service_role";

alter table "public"."users" drop constraint "users_academic_year_check";

alter table "public"."users" drop constraint "users_faculty_check";

alter table "public"."users" drop constraint "users_id_fkey";

alter table "public"."users" drop constraint "users_national_id_key";

alter table "public"."users" drop constraint "users_university_id_key";

alter table "public"."users" drop constraint "users_pkey";

drop index if exists "public"."users_national_id_key";

drop index if exists "public"."users_pkey";

drop index if exists "public"."users_university_id_key";

drop table "public"."users";


  create table "public"."automation_dates" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "date" timestamp with time zone not null,
    "available" boolean not null default true,
    "reserved_by" text
      );


alter table "public"."automation_dates" enable row level security;

alter table "public"."events" alter column "id" set generated by default;

CREATE UNIQUE INDEX automation_dates_pkey ON public.automation_dates USING btree (id);

alter table "public"."automation_dates" add constraint "automation_dates_pkey" PRIMARY KEY using index "automation_dates_pkey";

grant references on table "public"."automation_dates" to "anon";

grant trigger on table "public"."automation_dates" to "anon";

grant truncate on table "public"."automation_dates" to "anon";

grant delete on table "public"."automation_dates" to "authenticated";

grant insert on table "public"."automation_dates" to "authenticated";

grant references on table "public"."automation_dates" to "authenticated";

grant select on table "public"."automation_dates" to "authenticated";

grant trigger on table "public"."automation_dates" to "authenticated";

grant truncate on table "public"."automation_dates" to "authenticated";

grant update on table "public"."automation_dates" to "authenticated";

grant references on table "public"."automation_dates" to "service_role";

grant trigger on table "public"."automation_dates" to "service_role";

grant truncate on table "public"."automation_dates" to "service_role";

grant delete on table "public"."events" to "authenticated";

grant insert on table "public"."events" to "authenticated";

grant update on table "public"."events" to "authenticated";


  create policy "Enable delete for users based on user_id"
  on "public"."automation_dates"
  as permissive
  for delete
  to public
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."automation_dates"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."automation_dates"
  as permissive
  for select
  to public
using (true);



  create policy "Policy with table joins"
  on "public"."automation_dates"
  as permissive
  for update
  to public
using (true);



  create policy "Enable delete for users based on user_id"
  on "public"."events"
  as permissive
  for delete
  to public
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."events"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Give anon users access to JPG images in folder cojoot_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using (((bucket_id = 'event_images'::text) AND (storage.extension(name) = 'jpg'::text) AND (lower((storage.foldername(name))[1]) = 'public'::text) AND (auth.role() = 'anon'::text)));



  create policy "Give users authenticated access to folder cojoot_0"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check (((bucket_id = 'event_images'::text) AND (auth.role() = 'authenticated'::text)));



